sever:
  port: 8081
spring:
  ai:
    dashscope:
      # 配置通义千问API密钥
      api-key: sk-944809d73aa442a784fe7da2c15730d1
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8080  #服务地址