spring:
  main:
    web-application-type: none  # 必须禁用web应用类型
    banner-mode: off
  application:
    name: aitest
  resources.add-mappings: true
  servlet:
    connection-timeout: 60000
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    redis:
      host: 172.31.185.53
      port: 6370
      database: 0
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
      repositories:
        enabled: false
      password: 123456
  datasource:
    url: jdbc:mysql://172.31.186.43:4001/knowledge_base
    username: root
    password: Fpva_123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  neo4j:
    authentication:
      username: neo4j
      password: huizhang43
    uri: bolt://172.31.185.53:7687
  ai:
    vectorstore:
      redis:
        initializeSchema: true
    # 阿里：通义千问
    dash-scope:
      readTimeout: 300
      api-key: sk-944809d73aa442a784fe7da2c15730d1
      chat:
        options:
#          model: qwen-vl-plus
          model: qwen-max-longcontext
#          model: qwen-omni-turbo
          multi-model: true
      embedding:
        options:
          model: text-embedding-v2
      image:
        options:
          model: wanx-v1
    # 百度
    wenxin:
      api-key: sk-944809d73aa442a784fe7da2c15730d1
      chat:
        enabled: true 
        options:
          model: ernie-4.0-8k
    # 智谱
    zhipuai:
      api-key: cba2352448084d34aa65c70258287ede.dXpsHsXvtGrsRyI6
      chat:
        enabled: true
        options:
          model: GLM-4
    # 百度千帆
    qian-fan:
      api-key: J9YHblUSAi5tPyYs8YlIeXxR
      secret-key: zzR1PUzzmwFE4nYLvBvEVocbFj26CefQ
    # kimi   
    moonshot:
      api-key: sk-UBc794zelI1wZ8IPeDAcOVCEXXEKW4FLoc6YRWtDbzdCEPEY
    openai:
      #      Key分享自：https://pgthinker.me/2023/10/03/196/
      base-url: https://xiaoai.plus
      api-key: sk-7bkt0WIi6ep7xoKZ7M0SJRCf4JBrBuEQ1gDlgp2X29WnZNW4
    stabilityai:
      api-key: sk-IwlHn3bhbnOAqRPABJAjDouWuISW3KUbp8eWzV4BS2Z72aGG
    mcp:
      server:
        enabled: true
        resource-change-notification: true
        prompt-change-notification: true
        tool-change-notification: true
        name: mcp-demo-service
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/messages

logging:
  level:
    cn.dev33.satoken: OFF
    
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 自动续签
  auto-renew: true
  is-print: off

#文件上传公网云配置    
oss:
  accessKey: OUYPU3FXPVWJ83TA5ND7
  secretKey: SUIH41h1vhU9YV7iNFhP7ulHE1cEsyM8M6r4JDHd
  hostName: oss-beijing-m8.openstorage.cn
  timeout: 3600000
  bucketName: yys-oss-dev
  
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  client:
    ts:
      path: /ts.zip
    openapi:
      path: /openapi
      ui-path: /openapi-ui

code-assistant:
  project:
    project-path: D:\develop\workspace\workspace-ai\aitest
  arthas:
    url: http://localhost:8563/api
    password: arthas
    username: arthas